#ifndef LCC_ROBOTICS_KRYPTIK_2024_SRC_CONST_H_
#define LCC_ROBOTICS_KRYPTIK_2024_SRC_CONST_H_

#include <CrcLib.h>

using PIN = uint8_t;

// ============================
// PINS:
// ============================

// DRIVETRAIN
constexpr PIN FL_DRIVE_MOTOR = CRC_PWM_1;
constexpr PIN BL_DRIVE_MOTOR = CRC_PWM_2;
constexpr PIN BR_DRIVE_MOTOR = CRC_PWM_3;
constexpr PIN FR_DRIVE_MOTOR = CRC_PWM_4;

// FLYWHEEL
constexpr PIN FW_MOTOR_TOP = CRC_PWM_5;
constexpr PIN FW_MOTOR_BOT = CRC_PWM_6;

// PICKUP
constexpr PIN PICKUP_MOTOR = CRC_PWM_7;

// MULTIPLIER
constexpr PIN ELEV_MOTOR = CRC_PWM_8;
constexpr PIN MULTI_PLACER_MOTOR = CRC_PWM_9;
constexpr PIN MULTI_GUIDE_MOTOR = CRC_PWM_10;

constexpr PIN ELEV_ENCO_A = CRC_ENCO_A;
constexpr PIN ELEV_ENCO_B = CRC_ENCO_B;

// SORTING
constexpr PIN SORT_DOOR_MOTOR = CRC_PWM_11;
constexpr PIN SORT_DIVERT_MOTOR = CRC_PWM_12;

// ============================
// INPUTS:
// ============================

// tune
constexpr BUTTON VICTORY_BUTTON = BUTTON::START;

// die
constexpr BUTTON DIE_BUTTON = BUTTON::LOGO;

// drivelock
constexpr BUTTON PRECISION_CONTROL_L = BUTTON::HATL;
constexpr BUTTON PRECISION_CONTROL_R = BUTTON::HATR;

// PICKUP
constexpr BUTTON PICKUP_UP_BUTTON = BUTTON::COLORS_LEFT;
constexpr BUTTON PICKUP_DOWN_BUTTON = BUTTON::COLORS_DOWN;

// MULTIPLIER
constexpr ANALOG ELEV_MANUAL_CHANNEL = ANALOG::JOYSTICK2_Y;
constexpr BUTTON ELEV_NEXT_BUTTON = BUTTON::ARROW_UP;
constexpr BUTTON ELEV_PREV_BUTTON = BUTTON::ARROW_DOWN;

constexpr BUTTON MULTI_DEPLOY_BUTTON = BUTTON::ARROW_LEFT;
constexpr BUTTON MULTI_RETRACT_BUTTON = BUTTON::ARROW_RIGHT;

// sorting
constexpr BUTTON SORT_DOOR_BUTTON = BUTTON::COLORS_UP;
constexpr BUTTON SORT_DIVERT_BUTTON = BUTTON::COLORS_RIGHT;

// drivetrain
constexpr ANALOG FORWARD_CHANNEL = ANALOG::JOYSTICK1_Y;
constexpr ANALOG YAW_CHANNEL = ANALOG::JOYSTICK1_X;
constexpr ANALOG STRAFE_CHANNEL = ANALOG::JOYSTICK2_X;

// flywheel
constexpr BUTTON FW_FAR_BUTTON = BUTTON::L1;
constexpr BUTTON FW_CLOSE_BUTTON = BUTTON::R1;

constexpr ANALOG FW_FEED_CHANNEL = ANALOG::GACHETTE_L;
constexpr ANALOG FW_MANUAL_CHANNEL = ANALOG::GACHETTE_R;

#endif // LCC_ROBOTICS_KRYPTIK_2024_SRC_CONST_H_
