#pragma once

#include <CrcLib.h>

// ============================
// PINS:
// ============================

enum PINS : uint8_t {
    // DRIVETRAIN
    FL_DRIVE_MOTOR = CRC_PWM_1,
    BL_DRIVE_MOTOR = CRC_PWM_2,
    BR_DRIVE_MOTOR = CRC_PWM_3,
    FR_DRIVE_MOTOR = CRC_PWM_4,

    // FLYWHEEL
    FW_MOTOR_TOP = CRC_PWM_5,
    FW_MOTOR_BOT = CRC_PWM_6,

    FW_FEEDING_MOTOR = CRC_DIG_1,

    // PICKUP
    PICKUP_MOTOR = CRC_PWM_7,

    // MULTIPLIER
    ELEV_MOTOR = CRC_PWM_8,
    MULTI_PLACER_MOTOR = CRC_PWM_9,
    MULTI_GUIDE_MOTOR = CRC_PWM_10,

    ELEV_ENCO_A = CRC_ENCO_A,
    ELEV_ENCO_B = CRC_ENCO_B,

    // SORTING
    SORT_DOOR_MOTOR = CRC_PWM_11,
    SORT_DIVERT_MOTOR = CRC_PWM_12,
};

// ============================
// INPUTS:
// ============================

// tune
constexpr BUTTON VICTORY_BUTTON = BUTTON::START;

// die
constexpr BUTTON DIE_BUTTON = BUTTON::LOGO;

// drivelock
constexpr BUTTON PRECISION_CONTROL_L = BUTTON::HATL;
constexpr BUTTON PRECISION_CONTROL_R = BUTTON::HATR;

// PICKUP
constexpr BUTTON PICKUP_UP_BUTTON = BUTTON::COLORS_LEFT;
constexpr BUTTON PICKUP_DOWN_BUTTON = BUTTON::COLORS_DOWN;

// MULTIPLIER
constexpr BUTTON ELEV_UP_BUTTON = BUTTON::ARROW_UP;
constexpr BUTTON ELEV_DOWN_BUTTON = BUTTON::ARROW_DOWN;

constexpr BUTTON MULTI_DEPLOY_BUTTON = BUTTON::ARROW_LEFT;
constexpr BUTTON MULTI_RETRACT_BUTTON = BUTTON::ARROW_RIGHT;

// sorting
constexpr BUTTON SORT_DOOR_BUTTON = BUTTON::COLORS_UP;
constexpr BUTTON SORT_DIVERT_BUTTON = BUTTON::COLORS_RIGHT;

// drivetrain
constexpr ANALOG FORWARD_CHANNEL = ANALOG::JOYSTICK1_Y;
constexpr ANALOG YAW_CHANNEL = ANALOG::JOYSTICK1_X;
constexpr ANALOG STRAFE_CHANNEL = ANALOG::JOYSTICK2_X;

// flywheel
constexpr BUTTON FW_FAR_BUTTON = BUTTON::L1;
constexpr BUTTON FW_CLOSE_BUTTON = BUTTON::R1;

constexpr ANALOG FW_FEED_CHANNEL = ANALOG::GACHETTE_L;
constexpr ANALOG FW_MANUAL_CHANNEL = ANALOG::GACHETTE_R;
